server:
  port: 8765

spring:
  application:
    name: gateway-server
  profiles:
    active:
    - ${GATEWAY_PROFILE:dev}
info:
  component: Edge Server
 
zuul:
  routes:
    account:
      path: /accounts/**
      serviceId: account-service
    customer:
      path: /customers/**
      serviceId: customer-service
      
endpoints:
  routes:
    sensitive: false
      
ribbon: 
  eureka:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
    
security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


---
spring:
 profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    
---
spring:
  profiles: dev-pcf
  
#disable registering with eureka when running locally    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ribbon: 
  eureka:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  IsSecured: true

