server:
  port: 8765

spring:
  application:
    name: gateway-server
    
info:
  component: Edge Server
 
zuul:
  routes:
    account:
      path: /accounts/**
      serviceId: account-service
    customer:
      path: /customers/**
      serviceId: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    