server:
  port: 3333
  
spring:
  application:
    name: customer-service
  cloud:
    services:
      registrationMethod: route
    
feign:
  hystrix: 
    enabled: true
    
---
spring:
  profiles: dev

security:
  basic:
    enabled: false